# Generated by Django 5.0.3 on 2024-05-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='main_picture',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
